#############################################################################
# Makefile for building: libIronClock.so
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  IronClock.pro
# Template: app
# Command: C:\Qt\5.4\android_armv7\bin\qmake.exe -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile IronClock.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\NDK\android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc
CXX           = C:\NDK\android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -std=gnu++0x -g -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I..\..\Qt\5.4\android_armv7\mkspecs\android-g++ -I. -I..\..\Qt\5.4\android_armv7\include -I..\..\Qt\5.4\android_armv7\include\QtQuick -I..\..\Qt\5.4\android_armv7\include\QtWidgets -I..\..\Qt\5.4\android_armv7\include\QtGui -I..\..\Qt\5.4\android_armv7\include\QtQml -I..\..\Qt\5.4\android_armv7\include\QtNetwork -I..\..\Qt\5.4\android_armv7\include\QtCore -I. -I..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include -I..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include -I..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include
QMAKE         = C:\Qt\5.4\android_armv7\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = cp -f
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = libIronClock.so1.0.0
DISTDIR = C:\Qzone\IronClock\.tmp\libIronClock.so1.0.0
LINK          = C:\NDK\android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:\NDK\android-ndk-r10d/platforms/android-9/arch-arm/ -Wl,-soname,libIronClock.so -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\NDK\android-ndk-r10d/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -LC:\NDK\android-ndk-r10d/platforms/android-9/arch-arm//usr/lib -LC:/Qt/5.4/android_armv7/lib -lQt5Quick -Lc:\Utils\android\ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Lc:\Utils\android\ndk/platforms/android-9/arch-arm//usr/lib -LC:\Utils\icu32_53_1_mingw482\lib -LC:\utils\postgresql\pgsql\lib -LC:\utils\mysql\mysql\lib -Lc:\mingw491\mingw32\lib -LC:\Utils\pgsql\lib -LC:\temp\opensll-android-master\openssl-android-master\lib -LC:\Qt\5.4\android_armv7/lib -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = C:\NDK\android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\NDK\android-ndk-r10d/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.obj \
		qrc_qml.obj
DIST          =   main.cpp
QMAKE_TARGET  = libIronClock.so
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libIronClock.so


first: all
####### Implicit rules

.SUFFIXES: .obj .c .cpp .cc .cxx

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IronClock.pro ..\..\Qt\5.4\android_armv7\mkspecs\android-g++\qmake.conf ..\..\Qt\5.4\android_armv7\mkspecs\features\spec_pre.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\shell-unix.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\unix.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\linux.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\gcc-base.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\gcc-base-unix.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\qdevice.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\features\device_config.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\common\shell-win32.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\qconfig.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_declarative.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_enginio.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_enginio_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webview.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\features\qt_functions.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\qt_config.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\android-g++\qmake.conf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\spec_post.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\default_pre.prf \
		deployment.pri \
		..\..\Qt\5.4\android_armv7\mkspecs\features\resolve_config.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\default_post.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\qml_debug.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\declarative_debug.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\android\android.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\warn_on.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\qt.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\resources.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\moc.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\unix\opengl.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\uic.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\unix\thread.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\testcase_targets.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\exceptions.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\yacc.prf \
		..\..\Qt\5.4\android_armv7\mkspecs\features\lex.prf \
		IronClock.pro \
		qml.qrc \
		C:/Qt/5.4/android_armv7/lib/libQt5Quick.prl \
		C:/Qt/5.4/android_armv7/lib/libQt5Gui.prl \
		C:/Qt/5.4/android_armv7/lib/libQt5Core.prl \
		C:/Qt/5.4/android_armv7/lib/libQt5Qml.prl \
		C:/Qt/5.4/android_armv7/lib/libQt5Network.prl \
		C:/Qt/5.4/android_armv7/lib/libQt5Widgets.prl
	$(QMAKE) -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile IronClock.pro
..\..\Qt\5.4\android_armv7\mkspecs\features\spec_pre.prf:
..\..\Qt\5.4\android_armv7\mkspecs\common\shell-unix.conf:
..\..\Qt\5.4\android_armv7\mkspecs\common\unix.conf:
..\..\Qt\5.4\android_armv7\mkspecs\common\linux.conf:
..\..\Qt\5.4\android_armv7\mkspecs\common\gcc-base.conf:
..\..\Qt\5.4\android_armv7\mkspecs\common\gcc-base-unix.conf:
..\..\Qt\5.4\android_armv7\mkspecs\qdevice.pri:
..\..\Qt\5.4\android_armv7\mkspecs\features\device_config.prf:
..\..\Qt\5.4\android_armv7\mkspecs\common\shell-win32.conf:
..\..\Qt\5.4\android_armv7\mkspecs\qconfig.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_declarative.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_enginio.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_location.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\5.4\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\5.4\android_armv7\mkspecs\features\qt_functions.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\qt_config.prf:
..\..\Qt\5.4\android_armv7\mkspecs\android-g++\qmake.conf:
..\..\Qt\5.4\android_armv7\mkspecs\features\spec_post.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\exclusive_builds.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\default_pre.prf:
deployment.pri:
..\..\Qt\5.4\android_armv7\mkspecs\features\resolve_config.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\default_post.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\qml_debug.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\declarative_debug.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\android\android.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\warn_on.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\qt.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\resources.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\moc.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\unix\opengl.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\uic.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\unix\thread.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\testcase_targets.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\exceptions.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\yacc.prf:
..\..\Qt\5.4\android_armv7\mkspecs\features\lex.prf:
IronClock.pro:
qml.qrc:
C:/Qt/5.4/android_armv7/lib/libQt5Quick.prl:
C:/Qt/5.4/android_armv7/lib/libQt5Gui.prl:
C:/Qt/5.4/android_armv7/lib/libQt5Core.prl:
C:/Qt/5.4/android_armv7/lib/libQt5Qml.prl:
C:/Qt/5.4/android_armv7/lib/libQt5Network.prl:
C:/Qt/5.4/android_armv7/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile IronClock.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents main.cpp $(DISTDIR)\


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		timer.qml \
		main.qml \
		font\NEOTERIC.ttf \
		font\IDroid.otf
	C:\Qt\5.4\android_armv7\bin\rcc.exe -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.obj: main.cpp ..\..\Qt\5.4\android_armv7\include\QtWidgets\QApplication \
		..\..\Qt\5.4\android_armv7\include\QtWidgets\qapplication.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qcoreapplication.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qglobal.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qconfig.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qfeatures.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qsystemdetection.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qprocessordetection.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qcompilerdetection.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\utility \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++config.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\os_defines.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\cpu_defines.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_relops.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_pair.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\move.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\concept_check.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\boost_concept_check.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_types.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\type_traits \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\c++0x_warning.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdint \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\stdint.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\_types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\machine\_types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\_wchar_limits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\android\api-level.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\initializer_list \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\algorithm \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algobase.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functexcept.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_defines.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cpp_type_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\type_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\numeric_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator_base_funcs.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\debug.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\macros.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\functions.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_function.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\backward\binders.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\formatter.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\typeinfo \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\exception \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_lockfree_defines.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\exception_ptr.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\nested_exception.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hash_bytes.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ptr_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\predefined_ops.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algobase.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\features.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\basic_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\parallel.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compiletime_settings.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdio \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\stdio.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\cdefs.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\cdefs_elf.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\posix_types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\stddef.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\compiler.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\posix_types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\machine\kernel.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\sysmacros.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\types.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cstdlib \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\stdlib.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\string.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\malloc.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\alloca.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\strings.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\memory.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\limits \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cstdint \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\tags.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\settings.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithmfwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\compatibility.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sched.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\time.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\time.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\equally_split.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\find_selectors.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_algo.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\algorithmfwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_heap.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tempbuf.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_construct.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\new \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\alloc_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\alloc_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\memoryfwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\allocator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++allocator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\new_allocator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\random \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cmath \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\math.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\limits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\limits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\limits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\machine\internal_types.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\machine\limits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\syslimits.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\page.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\string \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stringfwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\char_traits.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\postypes.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cwchar \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\wchar.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\time.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\siginfo.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm-generic\siginfo.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\localefwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++locale.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\clocale \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\locale.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\iosfwd \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cctype \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\ctype.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream_insert.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\cxxabi_forced.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\range_access.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\atomicity.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\gthr-default.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\pthread.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\signal.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\signal.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm-generic\signal.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\sigcontext.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\ucontext.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\user.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\unistd.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\select.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\sys\sysconf.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\capability.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\pathconf.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\atomic_word.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\string_conversions.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cerrno \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\errno.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\linux\errno.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm\errno.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm-generic\errno.h \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\asm-generic\errno-base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\functional_hash.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_string.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\vector \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_uninitialized.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_vector.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_bvector.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\vector.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\vector \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\concurrence.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_sequence.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_iterator.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\vector \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\functional \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tuple \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\array \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\stdexcept \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\array \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\array \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\uses_allocator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hash_func.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_node.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_trace.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\unordered_map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ext\aligned_buffer.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\hashtable_policy.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\unordered_map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\unordered_map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_unordered_container.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\safe_local_iterator.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\unordered_base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\type_traits \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\functional_hash.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hashtable_policy.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\unordered_map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\fstream \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\istream \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ios \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ios_base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_classes.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\streambuf \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\cwctype \
		..\..\NDK\android-ndk-r10d\platforms\android-9\arch-arm\usr\include\wctype.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_base.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\streambuf_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\ctype_inline.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\locale_facets.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\basic_ios.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\ostream \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\ostream.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\istream.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\codecvt.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\basic_file.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\c++io.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\fstream.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_algos.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_state.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_hashtable_size.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_container_size.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\sstream \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\sstream.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_map_to_unordered_map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_size.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_vector_to_list.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_slist.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\impl\profiler_list_to_vector.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\iterator_tracker.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\libs\armeabi-v7a\include\bits\opt_random.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\random.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\numeric \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_numeric.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numeric \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\numericfwd.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\par_loop.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\workstealing.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_number.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\cmath \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\gamma.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\special_function_util.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\bessel_function.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\beta_function.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\ell_integral.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\exp_integral.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\hypergeometric.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\legendre_function.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\modified_bessel_func.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_hermite.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\poly_laguerre.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\riemann_zeta.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\tr1\random.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\for_each_selectors.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partial_sum.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algorithm \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\algo.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\sort.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\checkers.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_mergesort.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiway_merge.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\losertree.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\multiseq_selection.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\queue \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\deque \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_deque.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\deque.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\deque \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\deque \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_queue.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\quicksort.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\partition.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\balanced_quicksort.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\queue.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\omp_loop_static.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\search.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\random_shuffle.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\merge.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\unique_copy.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\parallel\set_operations.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qtypeinfo.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qtypetraits.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qsysinfo.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qlogging.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qflags.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qbasicatomic.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qgenericatomic.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_msvc.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_armv7.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_armv6.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_armv5.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_ia64.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_mips.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_x86.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_cxx11.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\atomic \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\atomic_base.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_gcc.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qatomic_unix.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qglobalstatic.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qmutex.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qnumeric.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qstring.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qchar.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qbytearray.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qrefcount.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qnamespace.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qarraydata.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qstringbuilder.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qobject.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qobjectdefs.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qlist.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qalgorithms.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qiterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\iterator \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stream_iterator.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\list \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_list.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\list.tcc \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\list \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\list \
		..\..\Qt\5.4\android_armv7\include\QtCore\qbytearraylist.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qcoreevent.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qscopedpointer.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qmetatype.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qvarlengtharray.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qcontainerfwd.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qisenum.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_tree.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\bits\stl_multimap.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\debug\multimap.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\map.h \
		..\..\NDK\android-ndk-r10d\sources\cxx-stl\gnu-libstdc++\4.9\include\profile\multimap.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qobject_impl.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qeventloop.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qwindowdefs.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qwindowdefs_win.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qpoint.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qsize.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qcursor.h \
		..\..\Qt\5.4\android_armv7\include\QtWidgets\qdesktopwidget.h \
		..\..\Qt\5.4\android_armv7\include\QtWidgets\qwidget.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qmargins.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpaintdevice.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qrect.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpalette.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qcolor.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qrgb.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qstringlist.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qdatastream.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qiodevice.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qpair.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qregexp.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qstringmatcher.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qbrush.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qvector.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qmatrix.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpolygon.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qregion.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qline.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qtransform.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpainterpath.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qimage.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpixelformat.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qpixmap.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qsharedpointer.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qshareddata.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qhash.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qfont.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qfontmetrics.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qfontinfo.h \
		..\..\Qt\5.4\android_armv7\include\QtWidgets\qsizepolicy.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qkeysequence.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qevent.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qvariant.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qmap.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qdebug.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qtextstream.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qlocale.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qset.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qcontiguouscache.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qurl.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qurlquery.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qfile.h \
		..\..\Qt\5.4\android_armv7\include\QtCore\qfiledevice.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qvector2d.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qtouchdevice.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qguiapplication.h \
		..\..\Qt\5.4\android_armv7\include\QtGui\qinputmethod.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\QQmlApplicationEngine \
		..\..\Qt\5.4\android_armv7\include\QtQml\qqmlapplicationengine.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qqmlengine.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qjsengine.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qjsvalue.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qtqmlglobal.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qqmlerror.h \
		..\..\Qt\5.4\android_armv7\include\QtQml\qqmldebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qrc_qml.obj: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.obj qrc_qml.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT)\libs\armeabi-v7a mkdir $(INSTALL_ROOT)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT)\libs\armeabi-v7a exit 1
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)\libs\armeabi-v7a\$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)\libs\armeabi-v7a\$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)\libs\armeabi-v7a 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

